export const SHORTCUTS = [
  { combo: "Shift + ?", action: "Toggle shortcut list" },
  { combo: "Shift + G", action: "Open Visitor Guide" },
  { combo: "Shift + H", action: "Fade in/out Hum" },
  { combo: "Shift + S", action: "Fade in/out SFX" },
  { combo: "Shift + R", action: "Fade in/out Ride" },
  { combo: "Shift + M", action: "Fade in/out Room" },
  { combo: "Shift + F", action: "Toggle Free Float Mode" },
  { combo: "Space", action: "Play / Pause" },
  { combo: "Arrow ←", action: "Previous track" },
  { combo: "Arrow →", action: "Next track" },
  { combo: "Shift + N", action: "Cycle portals" },
  { combo: "Shift + P", action: "Play panel SFX" },
  { combo: "Shift + B", action: "Blessing log" },
  { combo: "Shift + A", action: "Aura sync log" },
  { combo: "Shift + T", action: "Toggle Debug HUD" },
  { combo: "Shift + X", action: "Reset cockpit session" },
  { combo: "Shift + V", action: "Mute/Unmute ride video" },
];
